import type { Metadata } from "next";

import "@/app/globals.css";
import {NavBar} from "@/components/layout/NavBar";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    description: "Generated by create next app",
    title: "Create Next App",
};

export default function RootLayout({
       children,
   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <NavBar/>
            {children}
        </body>
        </html>
    );
}
