import { useGetAllProducts } from "@/hooks/products/useGet/useGetAll";
import { Metadata } from "next";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Big Store",
};

const Home = () => {
  // const { data, isLoading } = useGetAllProducts();
  //
  // if (isLoading) {
  //     return <div>Loading...</div>;
  // }
  //
  // return (
  //     <div>
  //         <h1>Products</h1>
  //         <ul>
  //             {data?.map((product) => (
  //                 <li key={product.id}>{product.title} - {product.rating.rate}</li>
  //             ))}
  //         </ul>
  //     </div>
  // );

  return (
    <div>
      <h1>Home</h1>
    </div>
  );
};

export default Home;
